FROM node

# Add chrome for testing
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable

# Set working Directory
WORKDIR /usr/app

# add bin files to the path so we can use 'ng'
ENV PATH /usr/app/node_modules/.bin:$PATH

# Copy and install
COPY package.json .
RUN npm install
COPY . .

CMD ["ng", "serve", "--host", "0.0.0.0"]